services:
  - type: web
    name: occasion-garantie
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_VERSION
        value: "18"
      - key: SMS_API_KEY
        value: sendsms_6034835d529bb41059bd737359e3b7556ede5b8e3a192e5f18f10720dc55f55e
      - key: SMS_SENDER_ID
        value: GOMOBILE
      - key: ADMIN_PHONE
        value: 212669017295
      - key: BANK_RIB
        value: "230 780 4092106211004600 62"
      - key: BANK_NAME
        value: CIH bank
      - key: BANK_HOLDER
        value: ABDELLAH EL MAHFOUDY
      - key: PING_INTERVAL
        value: "300000"
